### ISSUE TITLE
Error Loading Overlay

### ISSUE THREAD

**Issue by Yamoto07** [hibiyasleep/OverlayPlugin#12]
When attempting to show the DPS overlay, I get the below listed error. This occurs when clicking the "Show Overlay" checkbox on either the standard Mini Parse or the Spell Timer. HP overlay data is displaying correctly and ACT DPS graphing is working as well. I've reinstalled ACT from scratch and deleted all old files. 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at RainbowMage.OverlayPlugin.OverlayBase`1.<InitializeConfigHandlers>b__c(Object o, VisibleStateChangedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at RainbowMage.OverlayPlugin.OverlayConfigBase.set_IsVisible(Boolean value)
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2098.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Advanced Combat Tracker
    Assembly Version: 3.3.1.255
    Win32 Version: 3.3.1.255
    CodeBase: file:///D:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2094.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2093.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2098.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
GammaJul.LgLcd
    Assembly Version: 1.1.3.0
    Win32 Version: 1.1.3.0
    CodeBase: file:///D:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/GammaJul.LgLcd.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 0.85.5.452
    Win32 Version: 0.85.5.452
    CodeBase: file:///D:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/ICSharpCode.SharpZipLib.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
FFXIV_ACT_Plugin
    Assembly Version: 1.5.1.5
    Win32 Version: 3.3.1.255
    CodeBase: file:///D:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
OverlayPlugin
    Assembly Version: 0.3.3.12
    Win32 Version: 3.3.1.255
    CodeBase: file:///D:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
OverlayPlugin.Common
    Assembly Version: 0.3.3.12
    Win32 Version: 0.3.3.12
    CodeBase: file:///D:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin.Common.DLL
----------------------------------------
OverlayPlugin.Core
    Assembly Version: 0.3.3.12
    Win32 Version: 0.3.3.12
    CodeBase: file:///D:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin.Core.DLL
----------------------------------------
HtmlRenderer
    Assembly Version: 1.0.1.7
    Win32 Version: 1.0.1.7
    CodeBase: file:///D:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/HtmlRenderer.DLL
----------------------------------------
Xilium.CefGlue
    Assembly Version: 3.2272.2035.0
    Win32 Version: 3.2272.2035.0
    CodeBase: file:///D:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Xilium.CefGlue.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.1.19813
    CodeBase: file:///D:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Newtonsoft.Json.DLL
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Mitsukai** [comment]
Just leaving a comment to say I too am having the same problem. I've tried both the 32bit and 64bit versions, I've tried with and without running in Admin, I've tried a huge number of things, and can't figure out what's going on. 

Logs at: https://pastebin.com/f6T3vK91

**Comment by Skl3ros** [comment]
+1
Everything went well setting up ACT and I can see that it works in the main tab but the overlay itself simply won't work and I get the same error message when clicking on 'show overlay'.

**Comment by Grimoire-M** [comment]
Wanted to comment and say I have this error too. It appears to be due to a missing file from the rainbowmage plugin. Specifically "RainbowMage.OverlayPlugin.config.xml".

**Comment by hibiyasleep** [comment]
@Grimoire-M it's usually permission problem, try start your ACT as administrator.

**Comment by laiglinne-ff** [comment]
It's seems x86 BUG. Try on x64
