### ISSUE TITLE
NRE with 2 overlays of the same type

### ISSUE THREAD

**Issue by bsides** [hibiyasleep/OverlayPlugin#23]
If I have 2 MiniParse minions of the same "type", lots of NRE's pop out
![NRE](https://puu.sh/xjct7/a3b32aa278.png)

Tested with these 2: https://horizoverlay.now.sh and https://horizoverlay-test.now.sh

25/08/2017 12:29:51: Error: LOCAL: Update: System.NullReferenceException: Object reference not set to an instance of an object.
   at RainbowMage.OverlayPlugin.Overlays.MiniParseOverlay.CreateJsonData()
   at RainbowMage.OverlayPlugin.Overlays.MiniParseOverlay.CreateEventDispatcherScript()
   at RainbowMage.OverlayPlugin.Overlays.MiniParseOverlay.Update()
   at RainbowMage.OverlayPlugin.OverlayBase`1.<InitializeTimer>b__10(Object o, ElapsedEventArgs e)

**Comment by laiglinne-ff** [comment]
ugh... i can make this situation
![image](https://user-images.githubusercontent.com/20029869/35027429-04d2866a-fb94-11e7-80e8-7156b950db21.png)

**Comment by bsides** [comment]
Oh I'm sorry it's been a while and I'm not playing anymore in the PC so I couldn't test it now. Once I go back to it in June-ish I'll see if it's still happening. Thanks regardless!
